

-- EVERY DAY THE OVERDUE BILLING GETS PENALIZED WITH FEE (PHP 1.00 PER DAY)
SET GLOBAL EVENT_SCHEDULER = OFF;
SET GLOBAL EVENT_SCHEDULER = ON;
SHOW PROCESSLIST;

DROP EVENT IF EXISTS UPDATEOVERDUEBILLINGS;
CREATE EVENT UPDATEOVERDUEBILLINGS
	ON SCHEDULE EVERY 1 DAY
    STARTS DATE(NOW()) 
    
DO
    UPDATE BILLING SET TOTALDUE = TOTALDUE + 1 
    WHERE DATE(NOW()) > DATEDUE;
    
    
SELECT * FROM BILLING;
    